name: mobile
description: SnapDrama 모바일 앱
version: 0.1.0+1

# 이 패키지는 pub.dev에 퍼블리시되지 않음을 표시
publish_to: nones

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^7.0.0
  flutter_riverpod: ^2.3.0
  dio: ^5.1.0
  supabase_flutter: ^1.10.0
  shared_preferences: ^2.1.0
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.3.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_secure_storage: ^8.0.0
  google_fonts: ^4.0.0
  intl: ^0.20.2
  cached_network_image: ^3.2.3
  
  # 로컬 패키지
  shared:
    path: ../../packages/shared

# dependency_overrides:
  # shared:
    # path: ../../packages/shared


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  freezed: ^2.3.0
  json_serializable: ^6.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700 