name: mobile
description: SnapDrama 모바일 앱
version: 0.1.0+1

# 이 패키지는 pub.dev에 퍼블리시되지 않음을 표시
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # 상태 관리
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.4.0

  # 라우팅
  go_router: ^15.1.1

  # 백엔드 연동
  supabase_flutter: ^2.8.4
  dio: ^5.3.2

  # 유틸리티
  intl: 0.19.0
  flutter_secure_storage: ^10.0.0-beta.4
  shared_preferences: ^2.2.1
  logger: ^2.0.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # UI 관련
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  lottie: ^3.3.1
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  
  # 미디어 플레이어
  video_player: ^2.7.2
  chewie: ^1.7.1
  
  shared:
    path: ../../packages/shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.2
  custom_lint: ^0.7.5
  riverpod_lint: ^2.0.4
  freezed: ^3.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/i18n/
    
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700 